#!/usr/bin/python
# Distributed with a free-will license.
# Use it any way you want, profit or free, provided it fits in the licenses of its associated works.
# MS5611_01BXXX
# This code is designed to work with the MS5611_01BXXX_I2CS I2C Mini Module available from ControlEverything.com.
# https://www.controleverything.com/content/Analog-Digital-Converters?sku=MS5611-01BXXX_I2CS_A01#tabs-0-product_tabset-2

import smbus
import time
import paho.mqtt.client as mqtt

mqttuser = 'mqtt_username'
mqttpass = 'mqtt_password'


# Get I2C bus - place here your i2c bus (0 or 1)
bus = smbus.SMBus(0)

# MS5611_01BXXX address, 0x77(118)    replace 0x77 by 0x76 if your sensor has a different address
#		0x1E(30)	Reset command
bus.write_byte(0x77, 0x1E)

time.sleep(0.1)

# Read 12 bytes of calibration data
# Read pressure sensitivity
data = bus.read_i2c_block_data(0x77, 0xA2, 2)
C1 = data[0] * 256 + data[1]

# Read pressure offset
data = bus.read_i2c_block_data(0x77, 0xA4, 2)
C2 = data[0] * 256 + data[1]

# Read temperature coefficient of pressure sensitivity
data = bus.read_i2c_block_data(0x77, 0xA6, 2)
C3 = data[0] * 256 + data[1]

# Read temperature coefficient of pressure offset
data = bus.read_i2c_block_data(0x77, 0xA8, 2)
C4 = data[0] * 256 + data[1]

# Read reference temperature
data = bus.read_i2c_block_data(0x77, 0xAA, 2)
C5 = data[0] * 256 + data[1]

# Read temperature coefficient of the temperature
data = bus.read_i2c_block_data(0x77, 0xAC, 2)
C6 = data[0] * 256 + data[1]

# MS5611_01BXXX address, 0x77(118)
#		0x48(64)	Pressure conversion(OSR = 4096) command
bus.write_byte(0x77, 0x48)

time.sleep(0.1)

# Read digital pressure value
# Read data back from 0x00(0), 3 bytes
# D1 MSB2, D1 MSB1, D1 LSB
value = bus.read_i2c_block_data(0x77, 0x00, 3)
D1 = value[0] * 65536 + value[1] * 256 + value[2]

# MS5611_01BXXX address, 0x77(118)
#		0x58(64)	Temperature conversion(OSR = 4096) command
bus.write_byte(0x77, 0x58)

time.sleep(0.1)

# Read digital temperature value
# Read data back from 0x00(0), 3 bytes
# D2 MSB2, D2 MSB1, D2 LSB
value = bus.read_i2c_block_data(0x77, 0x00, 3)
D2 = value[0] * 65536 + value[1] * 256 + value[2]

dT = D2 - C5 * 256
TEMP = 2000 + dT * C6 / 8388608
OFF = C2 * 65536 + (C4 * dT) / 128
SENS = C1 * 32768 + (C3 * dT ) / 256
T2 = 0
OFF2 = 0
SENS2 = 0


# compensation algorythm as stated in datasheet
if TEMP >= 2000 :
	T2 = 0
	OFF2 = 0
	SENS2 = 0
elif TEMP < 2000 :
	T2 = (dT * dT) / 2147483648
	OFF2 = 5 * ((TEMP - 2000) * (TEMP - 2000)) / 2
	SENS2 = 5 * ((TEMP - 2000) * (TEMP - 2000)) / 4
	if TEMP < -1500 :
		OFF2 = OFF2 + 7 * ((TEMP + 1500) * (TEMP + 1500))
		SENS2 = SENS2 + 11 * ((TEMP + 1500) * (TEMP + 1500)) / 2

TEMP = TEMP - T2
OFF = OFF - OFF2
SENS = SENS - SENS2
pressure = ((((D1 * SENS) / 2097152) - OFF) / 32768.0) / 100.0
cTemp = TEMP / 100.0
fTemp = cTemp * 1.8 + 32


# barometer calculation => barometer is pressure at see level. 
# measurement has to be compensated with altitude 1mbar / 8.36m
# Barometer = Pressure + Altitude / 8.36
altitude = 111  #meter
barometer = pressure + altitude / 8.36


# Output data to screen uncomment if needed for debug
#print "Pressure : %.2f mbar" %pressure
#print "Barometer : %.2f mbar" %barometer
#print "Temperature in Celsius : %.2f C" %cTemp
#print "Temperature in Fahrenheit : %.2f F" %fTemp


# set here your mqtt broker address
broker_address="broker ip address"

# mqtt publish
mqttc = mqtt.Client("barometre")
mqttc.username_pw_set('mqttuser','mqttpass')
mqttc.connect(broker_address, 1883, 60)
#mqttc.loop_start()
#barometer value is rounded to keep only 2 number after decimal sign ( 0.01mbar )
# mqtt QoS = 0
mqttc.publish("weewx/barometer", round(barometer,2), 0)
mqttc.publish("weewx/pressure", round(pressure,2), 0)
mqttc.publish("weewx/inTemp", cTemp, 0)
mqttc.loop(5) #5sec timout
mqttc.disconnect()

